from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Owner(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    phone = models.IntegerField()
    rto = models.CharField(max_length=50)
    today_date = models.DateField(default=timezone.now) 
    new_vehicle_registration = models.BooleanField(default=False)
    vehicle_no = models.CharField(max_length=50,null=True)
    year_of_registration = models.IntegerField(null=True)
    chassis_no = models.CharField(max_length=50,null=True)
    engine_no = models.CharField(max_length=50,null=True)
    vehicle_model = models.CharField(max_length=50,null=True)
    red20mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    red50mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    yellow50mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    white80mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    class3 = models.IntegerField(default=0)
    white20mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    white50mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    red80mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    yellow80mm = models.DecimalField(max_digits=20,decimal_places=2,default=0)
    class4 = models.IntegerField(default=0)
    certificate_no = models.CharField(max_length=30,null=True)
    dealer_name = models.CharField(max_length=50,null=True)
    make = models.CharField(max_length=100,null=True) 
    front_image = models.ImageField(upload_to='images/',null=True)
    back_image = models.ImageField(upload_to='images/',null=True)
    left_image = models.ImageField(upload_to='images/',null=True)
    right_image = models.ImageField(upload_to='images/',null=True)
    rc_image = models.ImageField(upload_to='images/',null=True)
