# Generated by Django 4.2.3 on 2024-04-16 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('rto', models.CharField(max_length=50)),
                ('today_date', models.DateField(default=django.utils.timezone.now)),
                ('new_vehicle_registration', models.BooleanField(default=False)),
                ('vehicle_no', models.CharField(max_length=50, null=True)),
                ('year_of_registration', models.IntegerField(null=True)),
                ('chassis_no', models.CharField(max_length=50, null=True)),
                ('engine_no', models.CharField(max_length=50, null=True)),
                ('vehicle_model', models.CharField(max_length=50, null=True)),
                ('red20mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('red50mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('yellow50mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('white80mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('class3', models.IntegerField(default=0)),
                ('white20mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('white50mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('red80mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('yellow80mm', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('class4', models.IntegerField(default=0)),
                ('certificate_no', models.CharField(max_length=30, null=True)),
                ('dealer_name', models.CharField(max_length=50, null=True)),
                ('make', models.CharField(max_length=100, null=True)),
                ('front_image', models.ImageField(null=True, upload_to='images/')),
                ('back_image', models.ImageField(null=True, upload_to='images/')),
                ('left_image', models.ImageField(null=True, upload_to='images/')),
                ('right_image', models.ImageField(null=True, upload_to='images/')),
                ('rc_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
